# Generated by Django 3.0 on 2025-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='characteristics',
            field=models.ManyToManyField(to='mebel.Characteristics', verbose_name='характеристики'),
        ),
    ]
