# Generated by Django 3.0 on 2025-04-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0002_mebel_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='mebelangles',
            name='image',
            field=models.ImageField(upload_to='mebel_shots/', verbose_name='Изображение'),
        ),
    ]
