# Generated by Django 3.0 on 2025-04-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_auto_20250419_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
