# Generated by Django 3.0 on 2025-04-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_auto_20250419_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AddField(
            model_name='mebel',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mebel.Branch', verbose_name='Филлиал'),
        ),
    ]
