# Generated by Django 3.0 on 2025-04-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0005_auto_20250419_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='mebel',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='mebel',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.RemoveField(
            model_name='mebel',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='mebel',
            name='characteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mebel.Characteristics', verbose_name='характеристика'),
        ),
    ]
