# Generated by Django 3.0 on 2025-04-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0006_auto_20250419_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Филлиал', 'verbose_name_plural': 'Филлиалы'},
        ),
        migrations.AddField(
            model_name='slides',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mebel.Mebel', verbose_name='Ссылка'),
        ),
    ]
