# Generated by Django 3.0 on 2025-04-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0007_auto_20250420_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mebel',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='mebel',
            name='characteristics',
            field=models.ManyToManyField(null=True, to='mebel.Characteristics', verbose_name='характеристики'),
        ),
    ]
